name: znn_sdk_dart
description: Zenon SDK for Dart and Flutter
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  bip39: ^1.0.6
  hex: ^0.2.0
  bip32: ^2.0.0
  web_socket_channel: ^2.1.0
  args: ^2.1.1
  argon2_ffi_base: ^1.0.0+2
  cryptography: ^2.0.1
  pointycastle: ^3.1.3
  bech32: ^0.2.0
  sha3: ^0.2.0
  json_rpc_2: ^3.0.1
  collection: ^1.15.0-nullsafety.4
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  dart_code_metrics: ^4.3.3
